### ISSUE TITLE
Clarify setup

### ISSUE THREAD

**Issue by happybeing** [dan-da/crdt-php#1]
@dan-da the README didn't work as specified. For me on Ubuntu with no previous use of PHP or composer I needed to do the following:

# Install prerequisites on Ubuntu (PHP7 and composer):
sudo apt-get install php composer

# Get the code
mkdir -p ~/src/fuse/composer
cd ~/src/fuse/composer
composer require dan-da/crdt-php:dev-master

# Run the test
cd ~/src/fuse/composer/vendor/dan-da/crdt-php/src

# Print usage:
php tree.php

# Example test:
php tree.php test_concurrent_moves

**Comment by dan-da** [comment]
Thx, I've clarified the installation now.
